tag_bundles:
  [
    {
      name: 'B0',
      layout:
        [
          {id: 0, size: 0.06259},
          {id: 1, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B1',
      layout:
        [
          {id: 2, size: 0.06259},
          {id: 3, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B2',
      layout:
        [
          {id: 4, size: 0.06259},
          {id: 5, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B3',
      layout:
        [
          {id: 6, size: 0.06259},
          {id: 7, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B4',
      layout:
        [
          {id: 8, size: 0.06259},
          {id: 9, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B5',
      layout:
        [
          {id: 10, size: 0.06259},
          {id: 11, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B6',
      layout:
        [
          {id: 12, size: 0.06259},
          {id: 13, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B7',
      layout:
        [
          {id: 14, size: 0.06259},
          {id: 15, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B8',
      layout:
        [
          {id: 16, size: 0.06259},
          {id: 17, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B9',
      layout:
        [
          {id: 18, size: 0.06259},
          {id: 19, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B10',
      layout:
        [
          {id: 20, size: 0.06259},
          {id: 21, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B11',
      layout:
        [
          {id: 22, size: 0.06259},
          {id: 23, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B12',
      layout:
        [
          {id: 24, size: 0.06259},
          {id: 25, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B13',
      layout:
        [
          {id: 26, size: 0.06259},
          {id: 27, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B14',
      layout:
        [
          {id: 28, size: 0.06259},
          {id: 29, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B15',
      layout:
        [
          {id: 30, size: 0.06259},
          {id: 31, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B16',
      layout:
        [
          {id: 32, size: 0.06259},
          {id: 33, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B17',
      layout:
        [
          {id: 34, size: 0.06259},
          {id: 35, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B18',
      layout:
        [
          {id: 36, size: 0.06259},
          {id: 37, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B19',
      layout:
        [
          {id: 38, size: 0.06259},
          {id: 39, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B20',
      layout:
        [
          {id: 40, size: 0.06259},
          {id: 41, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B21',
      layout:
        [
          {id: 42, size: 0.06259},
          {id: 43, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B22',
      layout:
        [
          {id: 44, size: 0.06259},
          {id: 45, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B23',
      layout:
        [
          {id: 46, size: 0.06259},
          {id: 47, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B24',
      layout:
        [
          {id: 48, size: 0.06259},
          {id: 49, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B25',
      layout:
        [
          {id: 50, size: 0.06259},
          {id: 51, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B26',
      layout:
        [
          {id: 52, size: 0.06259},
          {id: 53, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B27',
      layout:
        [
          {id: 54, size: 0.06259},
          {id: 55, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B28',
      layout:
        [
          {id: 56, size: 0.06259},
          {id: 57, size: 0.06259, y: -0.11024} 
        ]
    },
    {
      name: 'B29',
      layout:
        [
          {id: 58, size: 0.06259},
          {id: 59, size: 0.06259, y: -0.11024} 
        ]
    }
  ]