tag_bundles:
  [
    {
      name: 'T000B294',
      layout:
        [
          {id: 0, size: 0.052},
          {id: 294, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T001B295',
      layout:
        [
          {id: 1, size: 0.052},
          {id: 295, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T000B296',
      layout:
        [
          {id: 0, size: 0.052},
          {id: 296, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T001B297',
      layout:
        [
          {id: 1, size: 0.052},
          {id: 297, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T000B298',
      layout:
        [
          {id: 0, size: 0.052},
          {id: 298, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T001B299',
      layout:
        [
          {id: 1, size: 0.052},
          {id: 299, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T000B300',
      layout:
        [
          {id: 0, size: 0.052},
          {id: 300, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T001B301',
      layout:
        [
          {id: 1, size: 0.052},
          {id: 301, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T000B302',
      layout:
        [
          {id: 0, size: 0.052},
          {id: 302, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T001B303',
      layout:
        [
          {id: 1, size: 0.052},
          {id: 303, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T000B304',
      layout:
        [
          {id: 0, size: 0.052},
          {id: 304, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T001B305',
      layout:
        [
          {id: 1, size: 0.052},
          {id: 305, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T000B306',
      layout:
        [
          {id: 0, size: 0.052},
          {id: 306, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T001B307',
      layout:
        [
          {id: 1, size: 0.052},
          {id: 307, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T000B308',
      layout:
        [
          {id: 0, size: 0.052},
          {id: 308, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T001B309',
      layout:
        [
          {id: 1, size: 0.052},
          {id: 309, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T000B310',
      layout:
        [
          {id: 0, size: 0.052},
          {id: 310, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T001B311',
      layout:
        [
          {id: 1, size: 0.052},
          {id: 311, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T000B312',
      layout:
        [
          {id: 0, size: 0.052},
          {id: 312, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T001B313',
      layout:
        [
          {id: 1, size: 0.052},
          {id: 313, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T000B314',
      layout:
        [
          {id: 0, size: 0.052},
          {id: 314, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T001B315',
      layout:
        [
          {id: 1, size: 0.052},
          {id: 315, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T000B316',
      layout:
        [
          {id: 0, size: 0.052},
          {id: 316, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T001B317',
      layout:
        [
          {id: 1, size: 0.052},
          {id: 317, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T000B318',
      layout:
        [
          {id: 0, size: 0.052},
          {id: 318, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T001B319',
      layout:
        [
          {id: 1, size: 0.052},
          {id: 319, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T000B320',
      layout:
        [
          {id: 0, size: 0.052},
          {id: 320, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T001B321',
      layout:
        [
          {id: 1, size: 0.052},
          {id: 321, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T000B322',
      layout:
        [
          {id: 0, size: 0.052},
          {id: 322, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T001B323',
      layout:
        [
          {id: 1, size: 0.052},
          {id: 323, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T000B324',
      layout:
        [
          {id: 0, size: 0.052},
          {id: 324, size: 0.052, y: -0.011} 
        ]
    },
    {
      name: 'T001B325',
      layout:
        [
          {id: 1, size: 0.052},
          {id: 325, size: 0.052, y: -0.011} 
        ]
    },
