# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 0, size: 0.176},
    {id: 1, size: 0.176},
    {id: 2, size: 0.176},
    {id: 3, size: 0.176},
    {id: 4, size: 0.176},
    {id: 5, size: 0.176},
    {id: 6, size: 0.176},
    {id: 7, size: 0.176},
    {id: 8, size: 0.176},
    {id: 9, size: 0.176},
    {id: 10, size: 0.176},
    {id: 11, size: 0.176},
    {id: 12, size: 0.176},
    {id: 13, size: 0.176},
    {id: 14, size: 0.176},
    {id: 15, size: 0.176},
    {id: 16, size: 0.176},
    {id: 17, size: 0.176},
    {id: 18, size: 0.176},
    {id: 19, size: 0.176},
    {id: 20, size: 0.176},
    {id: 21, size: 0.176},
    {id: 22, size: 0.176},
    {id: 23, size: 0.176},
    {id: 24, size: 0.176},
    {id: 25, size: 0.176},
    {id: 26, size: 0.176},
    {id: 27, size: 0.176},
    {id: 28, size: 0.176},
    {id: 29, size: 0.176},
    {id: 30, size: 0.176},
    {id: 31, size: 0.176},
    {id: 32, size: 0.176},
    {id: 33, size: 0.176},
    {id: 34, size: 0.176},
    {id: 35, size: 0.176},
    {id: 36, size: 0.176},
    {id: 37, size: 0.176},
    {id: 38, size: 0.176},
    {id: 39, size: 0.176},
    {id: 40, size: 0.176},
    {id: 41, size: 0.176},
    {id: 42, size: 0.176},
    {id: 43, size: 0.176},
    {id: 44, size: 0.176},
    {id: 45, size: 0.176},
    {id: 46, size: 0.176},
    {id: 47, size: 0.176},
    {id: 48, size: 0.176},
    {id: 49, size: 0.176},
    {id: 50, size: 0.176},
    {id: 51, size: 0.176},
    {id: 52, size: 0.176},
    {id: 53, size: 0.176},
    {id: 54, size: 0.176},
    {id: 55, size: 0.176},
    {id: 56, size: 0.176},
    {id: 57, size: 0.176},
    {id: 58, size: 0.176},
    {id: 59, size: 0.176},
    {id: 60, size: 0.176},
    {id: 61, size: 0.176},
    {id: 62, size: 0.176},
    {id: 63, size: 0.176},
    {id: 64, size: 0.176},
    {id: 65, size: 0.176},
    {id: 66, size: 0.176},
    {id: 67, size: 0.176},
    {id: 68, size: 0.176},
    {id: 69, size: 0.176},
    {id: 70, size: 0.176},
    {id: 71, size: 0.176},
    {id: 72, size: 0.176},
    {id: 73, size: 0.176},
    {id: 74, size: 0.176},
    {id: 75, size: 0.176},
    {id: 76, size: 0.176},
    {id: 77, size: 0.176},
    {id: 78, size: 0.176},
    {id: 79, size: 0.176},
    {id: 80, size: 0.176},
    {id: 81, size: 0.176},
    {id: 82, size: 0.176},
    {id: 83, size: 0.176},
    {id: 84, size: 0.176},
    {id: 85, size: 0.176},
    {id: 86, size: 0.176},
    {id: 87, size: 0.176},
    {id: 88, size: 0.176},
    {id: 89, size: 0.176},
  ]
# ## Tag bundle definitions
tag_bundles:
  [
  ]
